image: alpine:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo export const environment = { > src/environments/environment.prod.ts
    - echo production':' true, >> src/environments/environment.prod.ts
    - echo backend_url':' "'"$HEROKU_BACKEND_APP_NAME".heorkuapp.com'" >> src/environments/environment.prod.ts
    - echo }';' >> src/environments/environment.prod.ts
    - cat src/environments/environment.prod.ts
    - apk add ruby-dev ruby-rdoc git curl build-base
    - gem install dpl --pre
    - gem install bundler
    - dpl heroku api --api_key $HEROKU_API_KEY --app $HEROKU_APP_NAME
  only:
    - master
